spring:
  application:
    name: article-service
#  cloud:
#    config:
#    ####读取后缀
#      profile: pro
#      ####读取config-server注册地址
#      discovery:
#        service-id: config-service
#        enabled: true
#      label: master

#####    eureka服务注册地址
  datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: roof
      url: jdbc:mysql://localhost:3306/articleservice?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true

  redis:
    # Redis数据库索引，默认为0
    database: 0
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    # Redis密码，默认为空
    password:
    # Redis连接池最大连接数(负值表示没有限制
    jedis:
      pool:
        max-active: 10
        # 连接池最大阻塞等待时间
        max-wait: -1
        # 连接池最大空闲链接
        max-idle: 10
        # 连接池最小空闲链接
        min-idle: 0
    # 链接超时时间
    timeout: 10000

eureka:
  client:
    service-url:
           defaultZone: http://localhost:8761/eureka
server:
  port: 8883
###开启bus刷新
#management:
#  endpoints:
#    web:
#      exposure:
#        include: bus-refresh

  
