spring:
  application:
    name: user-service
  cloud:
    config:
    ####读取后缀
      profile: pro
      ####读取config-server注册地址
      discovery:
        service-id: config-service
        enabled: true
      label: master

#####    eureka服务注册地址    
eureka:
  client:
    service-url:
           defaultZone: http://localhost:8761/eureka
server:
  port: 8884
###开启bus刷新
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh

  
