server:
  port: 8769
spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/share

  profiles:
    active: native
  application:
    name: config-service







