###服务注册到eureka地址
eureka:
  client:
    service-url:
           defaultZone: http://localhost:8761/eureka
spring:
  application:
    ####注册中心应用名称
    name: config-service
  cloud:
    config:
      server:
        git:
          ###git环境地址
          uri: https://gitee.com/Sirius_hly/respo.git
          ####搜索目录
          search-paths:
            - share
      ####读取分支
      label: master
####端口号
server:
  port: 8888
