# remote git
#spring:
#  cloud:
#    config:
#      server:
#        git:
#          uri: https://git.coding.net/xiaoantimes/xiaoantimes-taichi
#          searchPaths: backend/repo
#          username: 124746406@qq.com
#          password:
#      label: master
# ---native
server:
  port: 8769
spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/share
  profiles:
    active: native
  application:
    name: config-service

management:
  security:
    enabled: false






